# Generated by Django 4.1.3 on 2023-09-29 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(verbose_name=datetime.timedelta(0)),
        ),
    ]
